<?php
$title = "Terms and conditions";
include('layouts/header.php');
?>

<section class="pageInfo-breadcrumbs">
    <div class="container-mid">
        <ul class="mb-0">
            <li><a href="#">Home</a></li>
            <li><span>Terms and conditions</span></li>
        </ul>
    </div>
</section>

<section class="sectionpadding20 staticContentType">
    <div class="container-mid">
        <div class="sectionHeading">
            <h1>Terms and conditions</h1>
        </div>
        <p>BY USING THE WEBSITE, YOU AGREE TO FOLLOWING TERMS AND CONDITIONS IN THE AGREEMENT. PLEASE NOTE THAT IN THE EVENT OF ANY CHANGE IN THIS AGREEMENT, WE WILL PUBLISH IT ONLINE ON THE WEBSITE. WE ENCOURAGE YOU TO REVIEW THE SITE PERIODICALLY FOR CHANGES IN THE TERMS AND CONDITIONS.</p>
        <p>This is a legal and binding document between you and Truck Junction. This document is an electronic record concerning the Information Technology Act, 2000 and the rules thereunder, as applicable, and the amended provisions on electronic records in various statutes, as amended by the Information Technology Act, 2000. This electronic record has been generated by a computer system and does not require any physical or digital signatures.</p>
        <p>This document has been published under the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the Rules and Regulations, Privacy Policy and Terms of Use for accessing or using the Truck Junction website.</p>

        <p><strong>Important</strong>The information provided on this web site includes, but is not limited to, the services provided by Truck Junction, and does not render any advice, certifications, guarantees or warranties on the content (as defined below) relating to the services, which Truck Junction makes available on this site. </p>

        <h2>Terms of Use</h2>

        <p>The Terms of Use govern the use of this site and the content contained herein. When you use this site, you acknowledge that you have read this agreement and accept and will be bound by the terms hereof. Truck Junction reserves the right to modify such terms from time to time, as may be required.</p>

        <h4>1. Purpose</h4>
        <p>As stated above, the contents provided on or through this site are solely for information purposes. They do not substitute for specific advice whether for investment, legal, taxation or other purposes and are not intended to provide you with any nature of certification, guarantee or warranty. By accessing, browsing and using this site, you agree and acknowledge that you understand this limited and restricted use and agree that you would not rely on the information and materials contained in this site for any purposes except as Truck Junction intends or specifies under this agreement. You further agree that you are ultimately responsible for determining your specific requirements and consequences in all actual matters. Truck Junction disclaims all liability for damages caused by the use of any content on the site. You agree that you are providing Truck Junction with personal details regarding your mobile phone address. You also agree that Truck Junction may use the information for automated analysis. You further agree that Truck Junction, to increase the value and benefit of this service to you, may provide your name and contact information to any third-party service provider.</p>

        <p>1.1 Truck Junction will provide services to research trucks, prices, technical specifications and other truck attributes. The services can include listing your used trucks online or browsing through the list of used trucks listed by users of Truck Junction. Truck Junction makes no claims regarding the accuracy of the data or the applicability of the information to any specific situation.</p>

        <p>1.2 Truck Junction may also allow the user to send SMS to the users' top callers or send an email to the users' friends, letting them know about the service.</p>

        <p>1.3 The site may provide certain Features ('site' and 'features' as defined under Section 2) that enable sending/receiving invites/solicitation messages/reminders to your contacts whose details, as required under the specific features, are submitted and expressly permitted by you to be so used. Once such a feature is selected and consented by you, you expressly agree that the feature shall enable sending one instant message and a maximum of 3 reminders.</p>

        <h4>2. Definitions</h4>
        <p>2.1 'Contents' or 'Content' shall mean any, and all information, data, text, software, music, sound, photographs, graphics, videos, messages, materials, news, notices, articles, contracts, forms, documents or other materials and information which may be viewed or downloaded on or through this site. Contents shall also include any email, messages, e-cards or any additional information furnished by a user to be displayed on the site by Truck Junction.</p>

        <p>2.2 'Feature' or 'Features': A 'Feature' may include any interactive, value addition service or other additional feature, introduced on the site.</p>

        <p>2.3 'Site' shall mean the internet site generally identified by the URL truck junction and all pages linked to URL's whose pages are posted and operated by Truck Junction or its agents.</p>

        <h4>3. Representations and Warranties</h4>
        <p>3.1 Truck Junction or any of its affiliates or associates or employees shall not be in any way responsible for any loss or damage that may arise to any person from any inadvertent error in the information contained in this site. The data from or through this site is provided 'as is'. Whether express or implied, all warranties regarding any matter about the site or content, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement are disclaimed.</p>

        <p>3.2 Truck Junction and its affiliates and associates shall not be liable, at any time, for any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communications line failure, theft or destruction or unauthorized access to, alteration of, or use of the information contained on the site. No representations, warranties, or guarantees are made concerning the accuracy, adequacy, reliability, completeness, suitability or applicability of the information to a particular situation.</p>

        <h4>4. Your Conduct</h4>
        <p>4.1 You may post your reviews or comments; and submit suggestions, ideas, questions, or other information, as long as the contents are not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and do not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of 'spam'. You shall not use a false email address, impersonate any person or entity, or otherwise mislead about the origin of the contents. However, you acknowledge that Truck Junction does not pre-screen the content, but that Truck Junction and its designees shall have the right (but not the obligation) in their sole discretion to accept, refuse, move, or remove any contents that are available via the site.</p>

        <p>4.2 You understand that all contents, whether publicly posted or privately transmitted, are the sole responsibility of the person from whom such contents originate. It means that you, and not Truck Junction, are entirely responsible for all contents you have provided Truck Junction to upload, post, transmit or otherwise make available via the site.</p>
        
        <p>4.3 You expressly agree not to use the site to: (i) harm any user in any manner either directly or indirectly; (ii) forge headers or otherwise manipulate identifiers to disguise the origin of any contents transmitted through the site; (iii) disrupt the normal flow of dialogue, cause a screen to 'scroll' faster than other users of the site can type, or otherwise act in a manner that negatively affects other users' ability to engage in real-time exchanges or 'stalk' or harass other users in any different way; (iv) interfere with or disrupt the site or servers or networks connected to the site, or disobey any requirements, procedures, policies or regulations of networks connected to the site; (v) upload or transmit any material that is deemed derogatory concerning the name, services or contents relating to or provided by Truck Junction; (vi) intentionally or unintentionally violate any applicable local, state, national or international laws.</p>

        <p>4.4 You expressly represent and warrant that: (i) you are capable to use this site following all terms and conditions herein concerning the access and use of this site and the services provided therein; and (ii) all information supplied by you in any correspondences or any other documentation to Truck Junction is correct, current, complete and accurate. You expressly agree that this clause shall survive any termination of this agreement.</p>

        <h4>5. Links to other Websites</h4>
        <p>This site may contain hyperlinks to websites operated by parties other than Truck Junction. The inclusion of hyperlinks to such websites does not imply Truck Junction's certification or endorsement of such websites nor any association with their operators. Neither Truck Junction, nor its affiliates, associates or employees provide any judgment or warranty regarding the authenticity or correctness of the content of other services or sites to which links are provided. A link to another service or site is not an endorsement of any products or services on such site or the site. You shall be solely responsible for any or all the consequences arising from your use of such hyperlinks to websites.</p>

        <h4>6. Websites Intellectual Property</h4>
        <p>All text, graphics, audio, design and other works on the site are Truck Junction's copyright unless otherwise indicated. Content on the site is for personal use only. Any alteration of the material or use of the material contained in the website for any commercial purpose is a violation of Truck Junction's copyright and/or its affiliates or associates or its third-party information providers. The content available on the site shall not be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way without obtaining the prior permission from Truck Junction. All responsibility and liability for any damages caused by downloading of any data is disclaimed.</p>

        <h4>7. License and Site Access</h4>
        <p>7.1 Truck Junction grants you a 'limited non-exclusive license' to access and make personal (non-commercial) use of this site for informational purposes and not modify either the whole or any portion of the site.</p>

        <p>7.2 The license shall not include: (i) any resale or commercial use of this site or its contents; or (ii) any derivative use of this site or its contents.</p>

        <p>7.3 You, your partners, employees, agents or any other person associated with you personally or professionally, may not, with or without compensation, prepare any derivative works from, or sell, lease, license, email, reproduce, duplicate, copy, resell, republish, transmit or distribute or otherwise exploit for any commercial purpose via any media, now known or unknown, any contents from this site to any other entity or individual. No contents or information on the site may be reproduced in any form or incorporated into any internet website or any other information retrieval system, either electronic or mechanical. It is a condition of your use of this site to not restrict or inhibit any other user from using this site.</p>

        <p>7.4 You shall not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Truck Junction and/or our affiliates without the express written consent of Truck Junction. You may not use any metatags or any other 'hidden text' utilizing Truck Junction's name or trademarks without the express written consent of Truck Junction. Any unauthorized use terminates the permission and the license granted by Truck Junction under this agreement to you.</p>

        <h4>8. Modifications on the Site</h4>
        <p>8.1 Truck Junction reserves the right to modify, suspend/cancel, or discontinue any or all sections, or service at any time without notice. Truck Junction reserves the right to make modifications and alterations in the site's information without notice. You agree that Truck Junction shall not be liable to you or any third party for any modification, suspension or discontinuance of the site.</p>

        <p>8.2 You expressly agree that you shall use any information provided on the site at your risk. You are advised to make proper enquiries and use the information provided on the site.</p>

        <p>8.3 From time to time Truck Junction may supplement its terms of use with additional terms about specific content (other terms). Such additional terms are hereby incorporated by reference into these Terms of Use.</p>

        <h4>9. Buying</h4>
        <p>Truck Junction strongly advises you not to test the site with false purchase requests, as it will put you at substantial personal legal risk. It is a crime to use a false name, other incorrect personal information to buy. Willfully entering erroneous or fictitious purchase requests may result in prosecution by Truck Junction. Please be aware that even if you do not give Truck Junction your real name, your web browser transmits a unique address to us, which law enforcement officials can use to identify you. As a seller, you certify that all information provided by you against your listed truck is correct. Individual sellers can list one truck at a time and need to make Truck Junction aware of its timely status.</p>

        <h4>10. Selling</h4>
        <p>As a registered member, you may list trucks for sale on the site. You must be legally able to sell the truck(s) you list for sale on our site. Listings may only include text descriptions, graphics and pictures that describe your trucks for sale. Sellers must list all trucks in an appropriate category on the site. Soliciting business offline or outside of the site, by indicating your contact details (e.g. contact phone number, address or email address) in the truck listing or elsewhere on the site other than in the Sell Truck Form is expressly prohibited. It would be considered as a breach of the User agreement. Sellers must keep all listed trucks in stock for successful fulfilment of sales. The trucks' listing description must not be misleading and must describe the actual condition of the product. If the truck description does not match the truck's exact condition, you agree to refund any amounts you may have received from the buyer.</p>

        <h4>11. Login Options</h4>
        <p>The Truck Junction Members login (if any) is for the reference of only registered Truck Junction's members. Truck Junction reserves the right to discontinue the member Login on account of violation of this agreement or any 'Code of Conduct' set by Truck Junction. Truck Junction reserves the right to take all measures necessary to prevent access to any content or portion of the site or terminate access to the site if the terms of use are not complied with or are contravened or there is any violation of copyright, trademark or other proprietary rights.</p>

        <h4>12. Disclaimer</h4>
        <p>12.1 Truck Junction makes no warranties or representations as to the contents of this site. Truck Junction assumes no liability or responsibility for any errors or omissions in the content on the site. The contents are provided 'as is' and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, or non-infringement. Truck Junction further makes no representation or warranty that any files, links or pointers available through this site will be free of viruses or other codes containing contaminated or destructive properties. Truck Junction disclaims all warranties, express or implied, to the fullest extent permissible under the applicable law. Truck Junction makes no warranty that-(i). The information will meet your requirements. (ii) The site will be uninterrupted, timely, secure, or error-free. (iii) The results that may be obtained from the use of the site will be accurate or reliable. (iv) The quality of any information obtained by you through the site will meet your expectations. (v) Any errors in the software will be corrected. Any material, contents or data downloaded or otherwise obtained from the site is subject to this agreement and done at your discretion and risk and that you will be solely responsible for any damage to your computer system or loss of data that results from the download of any such material. Truck Junction is not liable on the authenticity of such data. Without limiting the preceding, under no circumstances, shall Truck Junction be held responsible for any delay or failure in performance resulting directly or indirectly from acts of nature, forces, or causes beyond its reasonable control, including, without limitation, Internet failures, computer equipment failures, telecommunication equipment failures, other equipment failures, electrical power failures, strikes, labour disputes, riots, insurrections, civil disturbances, shortages of labour or materials, fires, floods, storms, explosions, acts of God, war, governmental actions, orders of domestic or foreign courts or tribunals, non-performance of third parties, or loss of or fluctuations in heat, light, or air conditioning.</p>

        <p>12.2 As per Truck Junction's email policy, email communication's integrity and security cannot be guaranteed via the public Internet as information can be intercepted, corrupted, lost, destroyed, arrive late or contain viruses. Truck Junction hereby disclaims any liability for the exact and complete transmission of the information contained in email messages or any delay in its receipt.</p>

        <h4>13. Limitation of Liability</h4>
        <p>Neither Truck Junction, nor its affiliates, employees, agents or consultants shall, in any event, be liable for any indirect, incidental or consequential damages such as, but not limited to, loss of business information, loss of goodwill, business interruption or loss of anticipated profits or benefits resulting from use of the site or any part or whole of the content or arising out of any breach of warranty even if Truck Junction or its affiliates, employees, agents or consultants have been advised of the possibility of such damages. Such limitation of liability shall apply whether the damages arise from use or misuse of or reliance on Truck Junction information, from the inability to use Truck Junction information, or from the interruption, suspension, or termination of access to the content or site (including such damages incurred by third parties). This limitation shall also apply, without limitation, to the costs of procurement of substitute content, loss of goodwill, loss of profits, or loss of data. Such limitation shall further apply to the performance or non-performance of Truck Junction or any information that appears on, or is linked or related in any way to, the site provided thereunder. Such limitation shall apply notwithstanding any failure of essential purpose of any limited remedy and to the fullest extent permitted by law.</p>

        <h4>14. Indemnity</h4>
        <p>You agree to indemnify and hold Truck Junction and its subsidiaries, affiliates, officers, agents, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of the contents you submit, email, transmit or make available through the site, your use of the site, your connection to the site, your violation of this agreement, or your violation of any rights of another user of this site.</p>

        <h4>15. Acknowledgement</h4>
        <p>The disclaimer and limited liability of Truck Junction set out in this agreement are fundamental elements of the bargain's basis for the content and access to the site. You agree that Truck Junction would not otherwise offer the content or the site on its present basis without such limitations. This clause shall survive any termination of this agreement.</p>

        <h4>16. Special Admonitions For International Use</h4>
        <p>Recognizing the Internet's global nature, you agree to comply with all local rules regarding online conduct. Expressly, you agree to abide by all applicable laws regarding the transmission of technical data exported from the country you reside in.</p>

        <h4>17. Severability</h4>
        <p>Any provision of this Agreement which is invalid, prohibited or unenforceable in any jurisdiction shall: (i) be ineffective in that jurisdiction to the extent of the invalidity, prohibition or unenforceability, (ii) be ineffective in that jurisdiction to the extent of the invalidity, prohibition or unenforceability and, (iii) not affect the validity of that provision in any other jurisdiction.</p>

        <h4>18. Governing Law and Arbitration</h4>
        <p>All legal proceedings shall be subject to the jurisdiction of the courts in Alwar, India and shall be governed by and construed in accordance with the laws of India and you agree to resolve the disputes under the Arbitration and Conciliation Act 1996. The venue for such arbitration shall be at Alwar, India.</p>

        <h4>19. Relationship</h4>
        <p>This Agreement or your use of this site does not constitute any joint venture, partnership, employment or agency relationship between you and Truck Junction.</p>

        <h4>20. Customer Registration</h4>
        <p>In the preview of the Telecom Regulatory Authority of India (TRAI) guidelines, I/We hereby authorize Truck Junction and its affiliates/partners /registered dealers, manufacturers or any other related player in automobiles or otherwise who are accessing the data under their association with Truck Junction to communicate with me/us through telephone/mobile, email, SMS or other modes of communication even if my/our number/numbers(s) is/are registered in the National Do Not Call Registry (NDNC) or www.nccptrai.gov.in.</p>

        <h4>21. Compliance with Laws</h4>
        <p>All dealing entities on the Truck Junction website are informed to comply with the applicable laws including but not limited to Foreign Exchange Management Act, 1999 and the rules made and notifications issued thereunder and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made thereunder, Foreign Contribution Regulation Act, 1976 and the rules made thereunder, Income Tax Act, 1961 and the rules made thereunder, Export-Import Policy of the government of India applicable to them respectively and the relevant amendments from time to time.</p>
        
    </div>
</section>

<?php include('layouts/footer.php'); ?>